# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 23:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='description',
            name='description',
            field=models.TextField(default=0, max_length=1000),
            preserve_default=False,
        ),
    ]
