# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 22:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0002_description_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='description',
            name='course_id',
        ),
        migrations.AddField(
            model_name='course',
            name='description_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='courses_app.Description'),
            preserve_default=False,
        ),
    ]
